/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LiveMigratorDiagnosticsSnapshot struct {
	TimeStamp int64 `json:"timeStamp,omitempty"`
	CollectionTime int64 `json:"collectionTime,omitempty"`
	Diagnostics []Diagnostic `json:"diagnostics,omitempty"`
	ImplClassName string `json:"implClassName"`
	DataAgentDiagnosticsSnapshots []DataAgentDiagnosticsSnapshot `json:"dataAgentDiagnosticsSnapshots,omitempty"`
}
