/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LinuxPressureDiagnostic struct {
	TimeStamp int64 `json:"timeStamp,omitempty"`
	Type_ string `json:"type"`
	Pressure []Pressure `json:"pressure,omitempty"`
	IowaitPercentage float64 `json:"iowaitPercentage,omitempty"`
}
