/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ThreadInfo struct {
	ThreadName string `json:"threadName,omitempty"`
	ThreadId int64 `json:"threadId,omitempty"`
	BlockedTime int64 `json:"blockedTime,omitempty"`
	BlockedCount int64 `json:"blockedCount,omitempty"`
	WaitedTime int64 `json:"waitedTime,omitempty"`
	WaitedCount int64 `json:"waitedCount,omitempty"`
	LockName string `json:"lockName,omitempty"`
	LockOwnerId int64 `json:"lockOwnerId,omitempty"`
	LockOwnerName string `json:"lockOwnerName,omitempty"`
	InNative bool `json:"inNative,omitempty"`
	Suspended bool `json:"suspended,omitempty"`
	ThreadState string `json:"threadState,omitempty"`
	StackTrace []ThreadInfoStackTrace `json:"stackTrace,omitempty"`
}
