/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Notification receiver properties
type EmailRegistrations struct {
	// Types of notifications that this email should be receiving
	Types []string `json:"types"`
	// Email addresses of receivers
	Addresses []string `json:"addresses"`
}
