/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// S3a filesystem properties
type S3aFilesystemProperties struct {
	// Access key
	AccessKey string `json:"accessKey,omitempty"`
	// Secret key
	SecretKey string `json:"secretKey,omitempty"`
	// Credentials Provider
	CredentialsProvider string `json:"credentialsProvider,omitempty"`
	// aws profile
	AwsProfile string `json:"awsProfile,omitempty"`
	// path to credentials file with profiles
	AwsCredentialsConfigFile string `json:"awsCredentialsConfigFile,omitempty"`
	// Bucket Name
	BucketName string `json:"bucketName,omitempty"`
	// s3 endpoint
	Endpoint string `json:"endpoint,omitempty"`
	// Additional filesystem properties
	AdditionalProperties map[string]string `json:"additionalProperties,omitempty"`
	// SQS queue used when using s3 as a source
	SqsQueue string `json:"sqsQueue,omitempty"`
	// Indicates an s3a compatibility filesystem type
	S3type string `json:"s3type,omitempty"`
	// Kafka server, host:port
	BootstrapServers string `json:"bootstrapServers,omitempty"`
	// Kafka's topic where s3 object change notifications are provided
	Topic string `json:"topic,omitempty"`
	// sqs endpoint
	SqsEndpoint string `json:"sqsEndpoint,omitempty"`
	// ldm will cleanup sqs queue after when the filesystem is deleted
	CleanUpSqsQueue bool `json:"cleanUpSqsQueue,omitempty"`
}
