/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FsType struct {
	Autoconfigurable bool `json:"autoconfigurable,omitempty"`
	Fs string `json:"fs,omitempty"`
	FsDescription string `json:"fsDescription,omitempty"`
	FsRestrictions []Exclusion `json:"fsRestrictions,omitempty"`
	MultipleSourceAllowed bool `json:"multipleSourceAllowed,omitempty"`
	SourceFilesystemExclusions []Exclusion `json:"sourceFilesystemExclusions,omitempty"`
}
