/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VerificationReportType string

// List of VerificationReportType
const (
	FULL_VerificationReportType VerificationReportType = "FULL"
	DISCREPANCIES_CSV_VerificationReportType VerificationReportType = "DISCREPANCIES_CSV"
	DISCREPANCIES_JSON_VerificationReportType VerificationReportType = "DISCREPANCIES_JSON"
	SUMMARY_VerificationReportType VerificationReportType = "SUMMARY"
	ALL_VerificationReportType VerificationReportType = "ALL"
)
