/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataAgentStatsRecordStore struct {
	SecondRecords []DataAgentStatsRecord `json:"secondRecords,omitempty"`
	MinuteRecords []DataAgentStatsRecord `json:"minuteRecords,omitempty"`
	HourlyRecords []DataAgentStatsRecord `json:"hourlyRecords,omitempty"`
	DailyRecords []DataAgentStatsRecord `json:"dailyRecords,omitempty"`
}
