/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FileTrackerPercentiles struct {
	Type_ string `json:"type,omitempty"`
	SuccessfulFileCount int32 `json:"successfulFileCount,omitempty"`
	FailedFileCount int32 `json:"failedFileCount,omitempty"`
	FileTrackerPercentile []FileTrackerPercentile `json:"fileTrackerPercentile,omitempty"`
}
