/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FileTrackerDiagnostic struct {
	TimeStamp int64 `json:"timeStamp,omitempty"`
	Type_ string `json:"type"`
	FileTrackers []FileTracker `json:"fileTrackers,omitempty"`
	FileSizePercentiles *FileTrackerPercentiles `json:"fileSizePercentiles,omitempty"`
	FileTransferRatePercentiles *FileTrackerPercentiles `json:"fileTransferRatePercentiles,omitempty"`
	RecentActivityByMigration map[string]int32 `json:"recentActivityByMigration,omitempty"`
	NumberOfActiveFileTransfers int32 `json:"numberOfActiveFileTransfers,omitempty"`
	LatencyPercentiles []FileTrackerPercentile `json:"latencyPercentiles,omitempty"`
}
