/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Verification struct {
	Id string `json:"id,omitempty"`
	MigrationId string `json:"migrationId,omitempty"`
	MigrationInternalId string `json:"migrationInternalId,omitempty"`
	Status *VerificationStatus `json:"status,omitempty"`
	CreatedTimestamp int64 `json:"createdTimestamp,omitempty"`
	StartedTimestamp int64 `json:"startedTimestamp,omitempty"`
	FinishedTimestamp int64 `json:"finishedTimestamp,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	StartedAt time.Time `json:"startedAt,omitempty"`
	FinishedAt time.Time `json:"finishedAt,omitempty"`
	Paths []string `json:"paths,omitempty"`
	IgnoreAfterTimestamp int64 `json:"ignoreAfterTimestamp,omitempty"`
	OriginalPaths []string `json:"originalPaths,omitempty"`
	VerificationDepth int32 `json:"verificationDepth,omitempty"`
	FilesOnSource int64 `json:"filesOnSource,omitempty"`
	DirectoriesOnSource int64 `json:"directoriesOnSource,omitempty"`
	BytesOnSource int64 `json:"bytesOnSource,omitempty"`
	FilesExcluded int64 `json:"filesExcluded,omitempty"`
	FilesExcludedExistsOnTarget int64 `json:"filesExcludedExistsOnTarget,omitempty"`
	FilesExcludedNotExistsOnTarget int64 `json:"filesExcludedNotExistsOnTarget,omitempty"`
	DataExcluded int64 `json:"dataExcluded,omitempty"`
	BytesExcluded int64 `json:"bytesExcluded,omitempty"`
	BytesExcludedExistsOnTarget int64 `json:"bytesExcludedExistsOnTarget,omitempty"`
	BytesExcludedNotExistsOnTarget int64 `json:"bytesExcludedNotExistsOnTarget,omitempty"`
	DirectoriesExcluded int64 `json:"directoriesExcluded,omitempty"`
	DirectoriesExcludedExistsOnTarget int64 `json:"directoriesExcludedExistsOnTarget,omitempty"`
	DirectoriesExcludedNotExistsOnTarget int64 `json:"directoriesExcludedNotExistsOnTarget,omitempty"`
	FilesOnTarget int64 `json:"filesOnTarget,omitempty"`
	DirectoriesOnTarget int64 `json:"directoriesOnTarget,omitempty"`
	BytesOnTarget int64 `json:"bytesOnTarget,omitempty"`
	FilesMissingOnTarget int64 `json:"filesMissingOnTarget,omitempty"`
	DirectoriesMissingOnTarget int64 `json:"directoriesMissingOnTarget,omitempty"`
	FilesMissingOnSource int64 `json:"filesMissingOnSource,omitempty"`
	DirectoriesMissingOnSource int64 `json:"directoriesMissingOnSource,omitempty"`
	FileSizeMismatches int64 `json:"fileSizeMismatches,omitempty"`
	TotalDiscrepancies int64 `json:"totalDiscrepancies,omitempty"`
}
