/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Local file system properties
type LocalFilesystemProperties struct {
	// Root path of local file system
	FsRoot string `json:"fsRoot,omitempty"`
	// Additional filesystem properties
	AdditionalProperties map[string]string `json:"additionalProperties,omitempty"`
}
