/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MigrationDiagnostic struct {
	TimeStamp int64 `json:"timeStamp,omitempty"`
	Type_ string `json:"type"`
	PendingRegions map[string]int32 `json:"pendingRegions,omitempty"`
	PendingRegionsMax map[string]int32 `json:"pendingRegionsMax,omitempty"`
	MigrationStateCounts map[string]int32 `json:"migrationStateCounts,omitempty"`
	FailedPaths map[string]int64 `json:"failedPaths,omitempty"`
	PathRetryCount map[string]int64 `json:"pathRetryCount,omitempty"`
	MigrationPathsRequeued map[string]int64 `json:"migrationPathsRequeued,omitempty"`
	ScannerProgress map[string]ScannerProgressMatrix `json:"scannerProgress,omitempty"`
	AverageFailedPaths int64 `json:"averageFailedPaths,omitempty"`
	AveragePendingRegions int64 `json:"averagePendingRegions,omitempty"`
	AveragePathRetries int64 `json:"averagePathRetries,omitempty"`
	TotalPendingRegions int64 `json:"totalPendingRegions,omitempty"`
	TotalFailedPaths int64 `json:"totalFailedPaths,omitempty"`
	TotalPathRetryCount int64 `json:"totalPathRetryCount,omitempty"`
}
