/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SourceCleanupReportFileMetadata struct {
	Descriptor *SourceCleanupReportFileDescriptor `json:"descriptor,omitempty"`
	Size int64 `json:"size,omitempty"`
	MigrationId string `json:"migrationId,omitempty"`
	MigrationExists bool `json:"migrationExists,omitempty"`
	Checksum int64 `json:"checksum,omitempty"`
	MigrationName string `json:"migrationName,omitempty"`
}
