/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MigrationRecord struct {
	MigrationId string `json:"migrationId,omitempty"`
	TimeStamp int64 `json:"timeStamp,omitempty"`
	MigrationStats *MigrationStats `json:"migrationStats,omitempty"`
}
