/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataAgentStatsRecord struct {
	TimeStamp int64 `json:"timeStamp,omitempty"`
	Stats *DataAgentStats `json:"stats,omitempty"`
	RecordPeriod string `json:"RecordPeriod,omitempty"`
}
