/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PendingRegion struct {
	PendingRegionId int64 `json:"pendingRegionId,omitempty"`
	Path string `json:"path,omitempty"`
	ActionPolicy string `json:"actionPolicy,omitempty"`
	DateCreated time.Time `json:"dateCreated,omitempty"`
}
