/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// HDFS file system properties
type HdfsFilesystemProperties struct {
	// Default filesystem
	DefaultFS string `json:"defaultFS,omitempty"`
	// FileSystem username to perform migration actions as
	User string `json:"user,omitempty"`
	// Kerberos principal
	KerberosPrincipal string `json:"kerberosPrincipal,omitempty"`
	// Kerberos keytab location
	KerberosKeyTab string `json:"kerberosKeyTab,omitempty"`
	// Success File GLOB pattern
	SuccessFile string `json:"successFile,omitempty"`
	// Additional filesystem properties
	AdditionalProperties map[string]string `json:"additionalProperties,omitempty"`
}
