/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type License struct {
	Id string `json:"id,omitempty"`
	ProductLicense string `json:"productLicense,omitempty"`
	LicenseSource string `json:"licenseSource,omitempty"`
	LicenseStatus string `json:"licenseStatus,omitempty"`
	Warning string `json:"warning,omitempty"`
	LastTimeChecked int64 `json:"lastTimeChecked,omitempty"`
	IsValid bool `json:"isValid,omitempty"`
	Components []LicenseComponent `json:"components,omitempty"`
	LicenseExceptionMessage string `json:"licenseExceptionMessage,omitempty"`
	InvalidReason string `json:"invalidReason,omitempty"`
	ExpiredReason string `json:"expiredReason,omitempty"`
	ExpiryDate string `json:"expiryDate,omitempty"`
}
