/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FileTracker struct {
	MigrationId string `json:"MigrationId,omitempty"`
	StatsType string `json:"StatsType,omitempty"`
	Path string `json:"Path,omitempty"`
	FileLength int64 `json:"FileLength,omitempty"`
	TransferId int64 `json:"TransferId,omitempty"`
	DataAgentName string `json:"DataAgentName,omitempty"`
	AttemptCount int64 `json:"AttemptCount,omitempty"`
	Thread string `json:"Thread,omitempty"`
	StartTime int64 `json:"StartTime,omitempty"`
	CompleteTime int64 `json:"CompleteTime,omitempty"`
	SourceEventCreationTimeStamp int64 `json:"SourceEventCreationTimeStamp,omitempty"`
	LdmEventCreationTimeStamp int64 `json:"LdmEventCreationTimeStamp,omitempty"`
	EventLatency int64 `json:"EventLatency,omitempty"`
	BytesTransferred int64 `json:"BytesTransferred,omitempty"`
	LastUpdate int64 `json:"LastUpdate,omitempty"`
	TimeBetweenUpdates int64 `json:"TimeBetweenUpdates,omitempty"`
	UpdateCount int64 `json:"UpdateCount,omitempty"`
	IsSuccessful bool `json:"IsSuccessful,omitempty"`
	Buckets []FileTrackerBucket `json:"Buckets,omitempty"`
	BytesPerSecond int64 `json:"BytesPerSecond,omitempty"`
	IsComplete bool `json:"IsComplete,omitempty"`
	IncomingTransportBytes int64 `json:"IncomingTransportBytes,omitempty"`
	OutgoingTransportBytes int64 `json:"OutgoingTransportBytes,omitempty"`
	DataTransferTiming *DataTransferTiming `json:"DataTransferTiming,omitempty"`
}
