/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RxTxTotals struct {
	TotalRxQueue int64 `json:"totalRxQueue,omitempty"`
	TotalTxQueue int64 `json:"totalTxQueue,omitempty"`
	Retrnsmt int64 `json:"retrnsmt,omitempty"`
}
