/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LicenseComponent struct {
	Warning string `json:"warning,omitempty"`
	LicenseType string `json:"licenseType,omitempty"`
	InvalidReason string `json:"invalidReason,omitempty"`
	IsValid bool `json:"isValid,omitempty"`
	LicenseStatus string `json:"licenseStatus,omitempty"`
	Type_ string `json:"type"`
}
