/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FileTrackerPercentile struct {
	Percentile int32 `json:"percentile,omitempty"`
	Value int64 `json:"value,omitempty"`
}
