/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GateActionStatus string

// List of GateActionStatus
const (
	CREATED_GateActionStatus GateActionStatus = "CREATED"
	INJECTED_GateActionStatus GateActionStatus = "INJECTED"
	AWAITING_DEPENDENT_REGIONS_GateActionStatus GateActionStatus = "AWAITING_DEPENDENT_REGIONS"
	SCHEDULED_GateActionStatus GateActionStatus = "SCHEDULED"
	COMPLETED_GateActionStatus GateActionStatus = "COMPLETED"
)
