/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// SmtpSecurityType : Security type of SMTP
type SmtpSecurityType string

// List of SmtpSecurityType
const (
	SSL_SmtpSecurityType SmtpSecurityType = "SSL"
	TLS_SmtpSecurityType SmtpSecurityType = "TLS"
	STARTTLS_ENABLED_SmtpSecurityType SmtpSecurityType = "STARTTLS_ENABLED"
	STARTTLS_REQUIRED_SmtpSecurityType SmtpSecurityType = "STARTTLS_REQUIRED"
	NONE_SmtpSecurityType SmtpSecurityType = "NONE"
)
