/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type MigrationGate struct {
	GateId string `json:"gateId,omitempty"`
	GatePath string `json:"gatePath,omitempty"`
	ActionStatus *GateActionStatus `json:"actionStatus,omitempty"`
	DependantRegions int32 `json:"dependantRegions,omitempty"`
	TimeCreated time.Time `json:"timeCreated,omitempty"`
	Complete bool `json:"complete,omitempty"`
	LastUpdated time.Time `json:"lastUpdated,omitempty"`
}
