/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TimeLicense struct {
	Warning string `json:"warning,omitempty"`
	LicenseType string `json:"licenseType,omitempty"`
	InvalidReason string `json:"invalidReason,omitempty"`
	IsValid bool `json:"isValid,omitempty"`
	LicenseStatus string `json:"licenseStatus,omitempty"`
	Type_ string `json:"type"`
	ExpiredReason string `json:"expiredReason,omitempty"`
	LastTimeChecked int64 `json:"lastTimeChecked,omitempty"`
	ExpireTime int64 `json:"expireTime,omitempty"`
	GracePeriodDays int64 `json:"gracePeriodDays,omitempty"`
	GracePeriodEndTime int64 `json:"gracePeriodEndTime,omitempty"`
}
