/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkStatus struct {
	TimeStamp int64 `json:"timeStamp,omitempty"`
	Type_ string `json:"type"`
	Uid int64 `json:"uid,omitempty"`
	Connections []NetworkConnection `json:"connections,omitempty"`
	ConnectionTotals map[string]RxTxTotals `json:"connectionTotals,omitempty"`
	CountTcpStates map[string]int32 `json:"countTcpStates,omitempty"`
}
