/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VerificationStatus string

// List of VerificationStatus
const (
	QUEUED_VerificationStatus VerificationStatus = "QUEUED"
	IN_PROGRESS_VerificationStatus VerificationStatus = "IN_PROGRESS"
	COMPLETE_VerificationStatus VerificationStatus = "COMPLETE"
	CANCELLED_VerificationStatus VerificationStatus = "CANCELLED"
)
