/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataAgentStats struct {
	TransferredBytes int64 `json:"transferredBytes,omitempty"`
	TransferredFiles int64 `json:"transferredFiles,omitempty"`
	TransferFailures int64 `json:"transferFailures,omitempty"`
	IncomingTransportBytes int64 `json:"incomingTransportBytes,omitempty"`
	OutgoingTransportBytes int64 `json:"outgoingTransportBytes,omitempty"`
}
