/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MigrationPatch struct {
	DelayedDeletionPeriod int32 `json:"delayedDeletionPeriod,omitempty"`
	RecurringPeriodSeconds int32 `json:"recurringPeriodSeconds,omitempty"`
	MigrationPriority *MigrationPriority `json:"migrationPriority,omitempty"`
}
