/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MigrationInfoList struct {
	Migrations []MigrationInfo `json:"migrations,omitempty"`
	Count int32 `json:"count,omitempty"`
}
