/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequeuingAction struct {
	MigrationId string `json:"migrationId,omitempty"`
	Path []string `json:"path,omitempty"`
	FirstRequeueTimestamp int64 `json:"firstRequeueTimestamp,omitempty"`
	LastRequeueTimestamp int64 `json:"lastRequeueTimestamp,omitempty"`
	ActionId int64 `json:"actionId,omitempty"`
	Action *ActionType `json:"action,omitempty"`
	NumberOfRequeues int64 `json:"numberOfRequeues,omitempty"`
	NSecondsRequeuing int64 `json:"nSecondsRequeuing,omitempty"`
	FailureMessage string `json:"failureMessage,omitempty"`
}
