/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataAgent struct {
	Name string `json:"name,omitempty"`
	Host string `json:"host,omitempty"`
	Port int32 `json:"port,omitempty"`
	Type_ *DataAgentType `json:"type,omitempty"`
	Version string `json:"version,omitempty"`
	Healthy bool `json:"healthy,omitempty"`
	Health *DataAgentHealth `json:"health,omitempty"`
	Security *DataAgentSecurity `json:"security,omitempty"`
}
