/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ThroughputBucket struct {
	PeakBytes int64 `json:"peakBytes,omitempty"`
	PeakFiles int64 `json:"peakFiles,omitempty"`
	TotalBytes int64 `json:"totalBytes,omitempty"`
	TotalFiles int64 `json:"totalFiles,omitempty"`
	PeakFilesBySize map[string]int64 `json:"peakFilesBySize,omitempty"`
	TotalFilesBySize map[string]int64 `json:"totalFilesBySize,omitempty"`
	ExcludedBytes int64 `json:"excludedBytes,omitempty"`
	ExcludedFiles int64 `json:"excludedFiles,omitempty"`
	ExcludedDirs int64 `json:"excludedDirs,omitempty"`
	ExcludedEvents int64 `json:"excludedEvents,omitempty"`
	RescannedFiles int64 `json:"rescannedFiles,omitempty"`
	RescannedDirs int64 `json:"rescannedDirs,omitempty"`
	ScannedFiles int64 `json:"scannedFiles,omitempty"`
	ScannedDirs int64 `json:"scannedDirs,omitempty"`
}
