/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FileTrackerBucket struct {
	Second int64 `json:"Second,omitempty"`
	BytesForSecond int64 `json:"BytesForSecond,omitempty"`
}
