/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataAgentType string

// List of DataAgentType
const (
	LOCAL_DataAgentType DataAgentType = "LOCAL"
	GRPC_DataAgentType DataAgentType = "GRPC"
)
