/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Target file system properties
type GcsFilesystemProperties struct {
	// JSON KeyFile location for GCS filesystem
	JsonKeyFile string `json:"jsonKeyFile,omitempty"`
	// P12 KeyFile location for GCS filesystem
	P12KeyFile string `json:"p12KeyFile,omitempty"`
	// GCS Bucket Name
	BucketName string `json:"bucketName"`
	// GCS Private key
	PrivateKey string `json:"privateKey,omitempty"`
	// GCS Private key id
	PrivateKeyId string `json:"privateKeyId,omitempty"`
	// GCS Service Account Email
	ClientEmail string `json:"clientEmail,omitempty"`
	// Additional filesystem properties
	AdditionalProperties map[string]string `json:"additionalProperties,omitempty"`
}
