/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RegexPatternType string

// List of RegexPatternType
const (
	JAVA_PCRE_RegexPatternType RegexPatternType = "JAVA_PCRE"
	AUTOMATA_RegexPatternType RegexPatternType = "AUTOMATA"
	GLOB_RegexPatternType RegexPatternType = "GLOB"
)
