/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MigrationProgress struct {
	TotalBytes int64 `json:"totalBytes,omitempty"`
	ExcludedBytes int64 `json:"excludedBytes,omitempty"`
	MigratedBytes int64 `json:"migratedBytes,omitempty"`
	MigrationClientBytesBinaryUnitValue string `json:"migrationClientBytesBinaryUnitValue,omitempty"`
	MigrationExcludedReadableBinaryValue string `json:"migrationExcludedReadableBinaryValue,omitempty"`
	MigratedPercentage int32 `json:"migratedPercentage,omitempty"`
	MigrationClientBytesBinaryUnits string `json:"migrationClientBytesBinaryUnits,omitempty"`
	MigrationTotalTransferredReadableBinaryUnits string `json:"migrationTotalTransferredReadableBinaryUnits,omitempty"`
	MigrationTotalTransferredReadableBinaryUnitValue string `json:"migrationTotalTransferredReadableBinaryUnitValue,omitempty"`
	MigrationTotalReadableBinaryUnits string `json:"migrationTotalReadableBinaryUnits,omitempty"`
	MigrationTotalBinaryUnitValue string `json:"migrationTotalBinaryUnitValue,omitempty"`
	MigrationMigratedReadableBinaryUnits string `json:"migrationMigratedReadableBinaryUnits,omitempty"`
	MigrationTotalTransferredProgressBinaryValue string `json:"migrationTotalTransferredProgressBinaryValue,omitempty"`
	MigrationTransferredProgressBinaryValue string `json:"migrationTransferredProgressBinaryValue,omitempty"`
	MigrationExcludedBinaryUnitValue string `json:"migrationExcludedBinaryUnitValue,omitempty"`
	TotalMigratedBytes int64 `json:"totalMigratedBytes,omitempty"`
	TotalMigratedBytesBinaryUnitValue string `json:"totalMigratedBytesBinaryUnitValue,omitempty"`
	EtaEstimate *MigrationDuration `json:"etaEstimate,omitempty"`
	DataMigratedDueToScan int64 `json:"dataMigratedDueToScan,omitempty"`
	DataMigratedDueToScanBinaryUnit string `json:"dataMigratedDueToScanBinaryUnit,omitempty"`
	DataMigratedDueToScanReadableValue string `json:"dataMigratedDueToScanReadableValue,omitempty"`
	OverallProgressSentValue int64 `json:"overallProgressSentValue,omitempty"`
	OverallProgressSentBinaryUnit string `json:"overallProgressSentBinaryUnit,omitempty"`
	OverallProgressSentReadableValue string `json:"overallProgressSentReadableValue,omitempty"`
	MigrationTotalScannedReadableBinaryUnits string `json:"migrationTotalScannedReadableBinaryUnits,omitempty"`
	MigrationTotalScannedProgressBinaryValue string `json:"migrationTotalScannedProgressBinaryValue,omitempty"`
	MigrationTotalScannedReadableBinaryUnitValue string `json:"migrationTotalScannedReadableBinaryUnitValue,omitempty"`
	TotalScannedBytes int64 `json:"totalScannedBytes,omitempty"`
	TotalScannedBytesBinaryUnitValue string `json:"totalScannedBytesBinaryUnitValue,omitempty"`
	Duration *MigrationDuration `json:"duration,omitempty"`
}
