/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataLicense struct {
	Warning string `json:"warning,omitempty"`
	LicenseType string `json:"licenseType,omitempty"`
	InvalidReason string `json:"invalidReason,omitempty"`
	IsValid bool `json:"isValid,omitempty"`
	LicenseStatus string `json:"licenseStatus,omitempty"`
	Type_ string `json:"type"`
	MigratedDataLimit int64 `json:"migratedDataLimit,omitempty"`
	ExpiredReason string `json:"expiredReason,omitempty"`
	LastTimeChecked int64 `json:"lastTimeChecked,omitempty"`
	MigratedDataSize int64 `json:"migratedDataSize,omitempty"`
	IsMigratedDataLimited bool `json:"isMigratedDataLimited,omitempty"`
	PercentMigratedDataUsed int32 `json:"percentMigratedDataUsed,omitempty"`
	MigratedDataRemaining int64 `json:"migratedDataRemaining,omitempty"`
	MigratedDataLimited bool `json:"migratedDataLimited,omitempty"`
}
