/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActionType string

// List of ActionType
const (
	CREATE_ActionType ActionType = "CREATE"
	MIGRATION_ActionType ActionType = "MIGRATION"
	MARKER_ActionType ActionType = "MARKER"
	NIL__ActionType ActionType = "NIL"
	UNLINK_ActionType ActionType = "UNLINK"
	RESCAN_ActionType ActionType = "RESCAN"
	RENAME_ActionType ActionType = "RENAME"
	METADATA_ActionType ActionType = "METADATA"
	DELAY_ActionType ActionType = "DELAY"
	RESCAN_UNLINK_ActionType ActionType = "RESCAN_UNLINK"
	GATE_ActionType ActionType = "GATE"
	LOCK_ActionType ActionType = "LOCK"
	VERIFY_ActionType ActionType = "VERIFY"
	MKDIRS_ActionType ActionType = "MKDIRS"
	NOT_PRESENT_ActionType ActionType = "NOT_PRESENT"
	IMMEDIATE_SOURCE_CLEANUP_ActionType ActionType = "IMMEDIATE_SOURCE_CLEANUP"
	DELAYED_SOURCE_CLEANUP_ActionType ActionType = "DELAYED_SOURCE_CLEANUP"
)
