/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Configuration properties for connection to SMTP server
type SmtpConfiguration struct {
	// Host of the SMTP server
	Host string `json:"host,omitempty"`
	// Port of the SMTP server
	Port int32 `json:"port,omitempty"`
	Security *SmtpSecurityType `json:"security,omitempty"`
	// Email that will be used by notification sender
	Email string `json:"email,omitempty"`
	Auth *SmtpAuth `json:"auth,omitempty"`
	// Prefix to be added to the e-mail subject
	SubjectPrefix string `json:"subjectPrefix,omitempty"`
}
