/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type RecurringMigrationIteration struct {
	StartTime time.Time `json:"startTime,omitempty"`
	CompleteTime time.Time `json:"completeTime,omitempty"`
	Iteration int32 `json:"iteration,omitempty"`
	DurationInSeconds int32 `json:"durationInSeconds,omitempty"`
}
