/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CpuLoadDiagnostic struct {
	TimeStamp int64 `json:"timeStamp,omitempty"`
	Type_ string `json:"type"`
	ProcessCpuLoad float64 `json:"processCpuLoad,omitempty"`
	ProcessCpuTime int64 `json:"processCpuTime,omitempty"`
	SystemCpuLoad float64 `json:"systemCpuLoad,omitempty"`
}
