/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"os"
)

type MultipartCreateFileBody struct {
	// Path to the file
	Path string `json:"path"`
	// File content
	FileBody **os.File `json:"fileBody"`
}
