/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Authentication credentials for connection to SMTP server
type SmtpAuth struct {
	// Authentication is enabled
	AuthEnabled bool `json:"authEnabled"`
	// Login
	Login string `json:"login,omitempty"`
	// Password
	Password string `json:"password,omitempty"`
}
