/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LiveMigratorRestException struct {
	Title string `json:"title,omitempty"`
	Status int32 `json:"status,omitempty"`
	Error_ int32 `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
}
