/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Notification struct {
	Level *NotificationLevel `json:"level,omitempty"`
	Type_ string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
	Id string `json:"id,omitempty"`
	TimeStamp int64 `json:"timeStamp,omitempty"`
	Code int32 `json:"code,omitempty"`
	Resolved bool `json:"resolved,omitempty"`
	UpdatedTimeStamp int64 `json:"updatedTimeStamp,omitempty"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	DateUpdated time.Time `json:"dateUpdated,omitempty"`
	DateCreated time.Time `json:"dateCreated,omitempty"`
}
