/*
 * LiveData Migrator
 *
 * LiveData Migrator API Documentation
 *
 * API version: 3.3.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActionStoreDiagnostic struct {
	TimeStamp int64 `json:"timeStamp,omitempty"`
	Type_ string `json:"type"`
	TotalUnExecutedEvents int64 `json:"totalUnExecutedEvents,omitempty"`
	MaxUnexecutedEvents int64 `json:"maxUnexecutedEvents,omitempty"`
	MigrationId string `json:"migrationId,omitempty"`
	Id string `json:"id,omitempty"`
}
